name: Replicator / Publish Helm Chart
on:
  push:
    tags:
      - '*.*.*'

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - 
        name: Install Helm
        uses: azure/setup-helm@v4
      -  
        name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - 
        name: Publish Helm Chart
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"